# Generated by Django 5.1.1 on 2024-11-03 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.region', verbose_name='Region'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='district',
        ),
        migrations.DeleteModel(
            name='Currier',
        ),
        migrations.AddField(
            model_name='user',
            name='district',
            field=models.ManyToManyField(to='apps.district', verbose_name='District'),
        ),
    ]
