# Generated by Django 5.1.1 on 2024-11-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_user_region_remove_user_district_delete_currier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manager_fee',
            field=models.PositiveIntegerField(blank=True, help_text='In sum', null=True, verbose_name='Admin_profit'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('admin', 'Admin'), ('customer', 'Customer'), ('operator', 'Operator'), ('currier', 'Currier'), ('manager', 'Manager')], default='customer', max_length=200, verbose_name='Type'),
        ),
    ]
