# Generated by Django 5.1.1 on 2024-11-26 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_currierstatisticuserproxy_user_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='manzil',
            field=models.TextField(blank=True, null=True, verbose_name='Talab'),
        ),
        migrations.AddField(
            model_name='order',
            name='talab',
            field=models.TextField(blank=True, null=True, verbose_name='Talab'),
        ),
    ]
