# Generated by Django 5.1.1 on 2024-09-09 08:36

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_order_created_at_order_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stream',
            name='slug',
        ),
        migrations.AddField(
            model_name='stream',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now()),
        ),
        migrations.AddField(
            model_name='stream',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
