# Generated by Django 5.1.1 on 2024-11-30 13:25

import apps.models.proxy_managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_delete_archivedorderproxy_delete_brokenorderproxy_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FreshStatisticProxy',
        ),
        migrations.CreateModel(
            name='AllStatisticProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Umumiy Statistika',
                'verbose_name_plural': 'Umumiy Statistikalar',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('apps.order',),
        ),
        migrations.CreateModel(
            name='BiznesStatisticProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Biznes Statistikasi',
                'verbose_name_plural': 'Biznes Statistikalari',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('apps.order',),
        ),
        migrations.CreateModel(
            name='FreshCurrierStatisticUserProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Fresh food Kurrierlar Statistikasi',
                'verbose_name_plural': 'Fresh food Kurrierlar Statistikasi',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('apps.user',),
            managers=[
                ('objects', apps.models.proxy_managers.CurrierUserManager()),
            ],
        ),
    ]
