# Generated by Django 5.1.1 on 2024-12-01 06:10

import apps.models.proxy_managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_delete_freshstatisticproxy_allstatisticproxy_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BiznesStatisticProxy',
        ),
        migrations.DeleteModel(
            name='CurrierStatisticUserProxy',
        ),
        migrations.DeleteModel(
            name='CurrierUserProxy',
        ),
        migrations.CreateModel(
            name='AllCurrierStatisticUserProxy',
            fields=[
            ],
            options={
                'verbose_name': 'AllCurrier Statistics',
                'verbose_name_plural': 'AllCurrier Statistics',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('apps.user',),
            managers=[
                ('objects', apps.models.proxy_managers.CurrierUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='MyBiznesStatisticProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Biznes Statistikasi',
                'verbose_name_plural': 'Biznes Statistikalari',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('apps.order',),
        ),
        migrations.CreateModel(
            name='MyCurrierUserProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Mening Kurrierlarim',
                'verbose_name_plural': 'Mening Kurrierlarim',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('apps.user',),
            managers=[
                ('objects', apps.models.proxy_managers.CurrierUserManager()),
            ],
        ),
    ]
