# Generated by Django 5.1.1 on 2024-12-01 13:48

import apps.models.proxy_managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_delete_biznesstatisticproxy_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllCurrierStatisticUserProxy',
        ),
        migrations.DeleteModel(
            name='FreshCurrierStatisticUserProxy',
        ),
        migrations.DeleteModel(
            name='MyCurrierUserProxy',
        ),
        migrations.DeleteModel(
            name='OperatorStatisticUserProxy',
        ),
        migrations.DeleteModel(
            name='OperatorUserProxy',
        ),
        migrations.CreateModel(
            name='BarchaKuryerlarStatistikasiUserProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Barcha Kuryerlar Statistikasi',
                'verbose_name_plural': 'Barcha Kuryerlar Statistikasi',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('apps.user',),
            managers=[
                ('objects', apps.models.proxy_managers.CurrierUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BarchaKuryerlarUserProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Barcha Kurrierlar',
                'verbose_name_plural': 'Barcha Kurrierlar',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('apps.user',),
            managers=[
                ('objects', apps.models.proxy_managers.CurrierUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='MeningKuryerlarimStatistikasiUserProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Mening Kuryerlarim Statistikasi ',
                'verbose_name_plural': 'Mening Kuryerlarim Statistikasi ',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('apps.user',),
            managers=[
                ('objects', apps.models.proxy_managers.CurrierUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='MeningKuryerlarimUserProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Mening Kuryerlarim',
                'verbose_name_plural': 'Mening Kuryerlarim',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('apps.user',),
            managers=[
                ('objects', apps.models.proxy_managers.CurrierUserManager()),
            ],
        ),
    ]
