# Generated by Django 5.1.1 on 2024-12-03 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_delete_allcurrierstatisticuserproxy_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllStatisticProxy',
        ),
        migrations.CreateModel(
            name='UmumiyRaqamlarProxy',
            fields=[
            ],
            options={
                'verbose_name': 'UmumiyRaqamlar',
                'verbose_name_plural': 'UmumiyRaqamlar',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('apps.order',),
        ),
    ]
